version: "3.6"

services:
  api:
    networks:
      - backend
    image: deep-thoughts:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/deep-thoughts
  postgres:
    networks:
      - backend
    ports:
      - 5432:5432
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgres

  client:
    networks:
      - backend
    image: deepthought-client:latest
    ports:
      - 3000:3000
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development

volumes:
  db_data:

networks:
  backend:
